### ISSUE TITLE
server error 500

### ISSUE THREAD

**Issue by princewaleed77** [Mbere250/ijaboCropTool#1]
i cannot refresh my view i have server erro and initilization sentence is not active .. and always stuck with 
@if(session['status'])
code
@endif
if i delete this check it gose to another word
![IMG-20210615-WA0007](https://user-images.githubusercontent.com/74210232/122112853-9987f980-ce21-11eb-8825-ff9252d9fe0f.jpeg)

[
![IMG-20210615-WA0009](https://user-images.githubusercontent.com/74210232/122113605-9e00e200-ce22-11eb-8458-2079575ab560.jpg)
](url)
![IMG-20210615-WA0003](https://user-images.githubusercontent.com/74210232/122113638-a78a4a00-ce22-11eb-8e1e-f819b30f9d8a.jpg)
![IMG-20210615-WA0002](https://user-images.githubusercontent.com/74210232/122113668-b244df00-ce22-11eb-9d0f-a7284ea3d2f1.jpg)
![IMG-20210615-WA0001](https://user-images.githubusercontent.com/74210232/122113694-b83ac000-ce22-11eb-9d25-791509670918.jpg)

**Comment by princewaleed77** [comment]
i found the error thanks it was a sentax error

**Comment by sawastacks** [comment]
Ok, good
