### ISSUE TITLE
Size image become Larger

### ISSUE THREAD

**Issue by bagussona** [Mbere250/ijaboCropTool#3]
Hello, can you help me, overall.. everything is oke, the pckg is working well, but the size of the uploaded photo becomes larger. how to reduce the size of the photo using IjaboCropTool? Thanks.

**Comment by sawastacks** [comment]
you will need to use laravel image intervention library
https://youtu.be/s0vyQFWxRj8

**Comment by bagussona** [comment]
No sir, I mean, it's not the media size that turns out to be large. But File Size in KB. Example: The initial size was 50KB (.jpg file) after cropping its increased to 500KB (.png file).

**Comment by bagussona** [comment]
I have solve it by reducing the image quality. But, with Consequence -> the image becomes blurry. hahaha
